# Generated by Django 2.2.28 on 2024-03-20 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(default='', max_length=255, unique=True)),
                ('building_description', models.TextField(default='')),
                ('building_image', models.ImageField(blank=True, default='{{ MEDIA_URL }}building_images/default-image.jpg', upload_to='building_images')),
                ('google_map', models.CharField(default='', max_length=255)),
                ('building_instagram', models.URLField(blank=True, default='https://www.instagram.com/uofglasgow?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==')),
                ('building_website', models.URLField(blank=True)),
                ('building_views', models.IntegerField(default=0)),
                ('building_likes', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('building_slug', models.SlugField(default='', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Buildings',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('picture', models.ImageField(blank=True, default='Website/mediacat.jpg', upload_to='profile_images')),
                ('upvotes', models.IntegerField(default=0)),
                ('images', models.ImageField(blank=True, upload_to='')),
                ('bio', models.CharField(max_length=100)),
                ('reviews', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_commented', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Review.Building')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_title', models.CharField(max_length=225)),
                ('room_picture', models.ImageField(blank=True, default='', upload_to='room_images')),
                ('room_views', models.IntegerField(default=0)),
                ('room_likes', models.IntegerField(default=0)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Review.Building')),
            ],
            options={
                'verbose_name_plural': 'Building Rooms',
            },
        ),
    ]
