# Generated by Django 2.2.28 on 2024-03-18 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name_plural': 'Buildings'},
        ),
        migrations.RenameField(
            model_name='building',
            old_name='description',
            new_name='building_description',
        ),
        migrations.RemoveField(
            model_name='building',
            name='image',
        ),
        migrations.RemoveField(
            model_name='building',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='building',
            name='name',
        ),
        migrations.RemoveField(
            model_name='building',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='building',
            name='website',
        ),
        migrations.AddField(
            model_name='building',
            name='building_image',
            field=models.ImageField(blank=True, default='{{ MEDIA_URL }}building_images/default-image.jpg', upload_to='building_images'),
        ),
        migrations.AddField(
            model_name='building',
            name='building_instagram',
            field=models.URLField(blank=True, default='https://www.instagram.com/uofglasgow?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw=='),
        ),
        migrations.AddField(
            model_name='building',
            name='building_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='building_name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='building',
            name='building_slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='building',
            name='building_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='building_website',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='BuildingRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_title', models.CharField(max_length=225)),
                ('room_picture', models.ImageField(blank=True, default='', upload_to='room_images')),
                ('room_views', models.IntegerField(default=0)),
                ('room_likes', models.IntegerField(default=0)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Review.Building')),
            ],
            options={
                'verbose_name_plural': 'Building Rooms',
            },
        ),
    ]
