# Generated by Django 2.2.28 on 2024-03-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='media/mediacat.jpg', upload_to='profile_images'),
        ),
    ]
