# Generated by Django 2.2.28 on 2024-03-09 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='building',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='building',
            name='google_map',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='building',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='building_images'),
        ),
        migrations.AddField(
            model_name='building',
            name='instagram',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='building',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
        migrations.AddField(
            model_name='building',
            name='website',
            field=models.CharField(default='', max_length=255),
        ),
    ]
