# Generated by Django 2.2.28 on 2024-03-09 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0002_auto_20240309_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Review.Building'),
        ),
    ]
