# Generated by Django 2.2.28 on 2024-03-19 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Review', '0002_auto_20240318_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_buildings', to=settings.AUTH_USER_MODEL),
        ),
    ]
