# Generated by Django 4.2.11 on 2024-03-15 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Review', '0003_comment_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_ID',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_ID',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='Website/mediacat.jpg', upload_to='profile_images'),
        ),
    ]
