# Generated by Django 2.2.28 on 2024-03-19 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0003_building_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='uploader',
        ),
    ]
