# Generated by Django 2.2.28 on 2024-03-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0010_auto_20240320_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='building_dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
