# Generated by Django 2.2.28 on 2024-03-22 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0011_building_building_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='building_views',
        ),
        migrations.RemoveField(
            model_name='buildingrooms',
            name='room_likes',
        ),
        migrations.RemoveField(
            model_name='buildingrooms',
            name='room_views',
        ),
    ]
